all:
  children:
    # ----------------------------------------------------------------
    # Test Infrastructure
    # ----------------------------------------------------------------
    
    ansible_controller:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    trex_server:
      hosts:
        trex-01:
          ansible_host: 10.1.1.10

    k6_server:
      hosts:
        k6-01:
          ansible_host: 10.1.1.70

    app_server:
      hosts:
        app-01:
          ansible_host: 10.1.1.60

    mikrotik_dut:
      hosts:
        mikrotik-01:
          ansible_host: 10.1.1.118
          ansible_user: scadmin
          # ansible_ssh_pass: Scadmin
          ansible_connection: ansible.netcommon.network_cli
          ansible_network_os: community.routeros.routeros

    #network_switches:
    #  hosts:
    #    cisco-sw-01:
    #      ansible_host: 10.1.1.40
    #      ansible_network_os: ios